name: geo_view
description: "Aplicativo Flutter para visualização de mapas e dados geográficos."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_riverpod: ^2.5.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/geo/areas.geojson
